# Generated by Django 4.2.5 on 2023-10-04 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('red_circle_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('has_children', models.BooleanField(default=False)),
                ('is_root', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('red_circle_parent_id', models.CharField(default=None, max_length=255, null=True)),
                ('parent_name', models.CharField(default=None, max_length=255, null=True)),
                ('type', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_circle_product_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('unit_cost', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('size', models.FloatField(null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('source', models.CharField(default='Red Circle API', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='grocery.category')),
            ],
        ),
    ]
